CXX = g++
CXXFLAGS = -O2
RM = rm -f
all: 1 2 3 4 5

1:
	$(CXX) $(CXXFLAGS) 1.cpp -o 1
2:
	$(CXX) $(CXXFLAGS) 2.cpp -o 2
3:
	$(CXX) $(CXXFLAGS) 3.cpp -o 3
4:
	$(CXX) $(CXXFLAGS) 4.cpp -o 4
5:
	$(CXX) $(CXXFLAGS) 5.cpp -o 5


clean:
	$(RM) 1 2 3 4 5


